### PR TITLE
SSU refactoring

### PR DESCRIPTION
**Pull request by anonimal**
Hi @EinMByte,

As discussed in https://github.com/monero-project/kovri/issues/140, I'm not yet finished but I thought it would be better to start a PR and leave it open until you were able to do some work and then you could close the PR at will (in order to save time with merging/rebasing, etc).

I've also included summaries (and a couple of important comments) in the commits.

The next issue I'll focus on is finishing much more documentation and, if you haven't fixed the segfault yet, _then_ I'll take a stab at the breakage (looks like fun...).

### CODE REVIEW

**Comment by EinMByte** [comment]
@anonimal I will remain more-or-less inactive until Friday.
I'll make sure to merge before continuing since I don't have any uncommitted changes anyway.

**Comment by anonimal** [comment]
Hi again @EinMByte,

I ended up finishing other more important refactor work (more important that documenting work) but haven't started the larger documentation phase yet - nor have I gotten a chance to debug. For documentation, I'll stick almost entirely to headers for now but what I'm more curious to know is how we can reclassify the purpose of every SSU file, fine-tune its organization, and find areas for re-implementation; something that will complement SSUPacket and hopefully narrow down the amount of code needed  (everything that isn't SSUPacket (or isn't what we worked on) is still a mess).

Since it's Friday, I will watch this PR closely and once you merge, cease to work on SSU until we can open further communication.

**Comment by EinMByte** [comment]
@anonimal I'll most likely merge the PR tomorrow.
About the other SSU files:  eventually I want to significantly shorten `SSUSession.cpp` and `SSUData.cpp`. At this point I don't know yet exactly what additional refactoring will be necessary to achieve that. I'll start by simplifying all of the packet builder code using `SSUPacket`, but some of the signature-building code will also have to be moved. `SSUData` must undergo some large changes. The fragment parsing code has already been rewritten and seems to be working, but it hasn't been integrated with `SSUData`.

**Comment by anonimal** [comment]
That all sounds great; I completely understand and agree with that direction. One thing I'd like to work on are more sanity tests, but I'd like to pursue that after the bulkier design work is done (and if you don't disagree with me working on them (I did see several of your TODO's regarding overflow)).

I've pushed 602df06 with tl;dr notes (as usual) in the commit message. I'm done for the evening but I'll check-in tomorrow to see where we are.  Hopefully we can chat more on Sunday. :smile:

**Pull request merged**
